import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CardBlog from "@/component/Card/CardBlog";
import {Col, Container, Grid} from "@mantine/core";
import {useEffect, useState} from "react";
import {useAllBlog} from "@/graphql";
import {sortedData} from "@/lib/helpers/sort";
import {NavBar} from "@/component/Header";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [searchValue, setSearchValue] = useState<string>("");
    const [allBlogs, setAllBlogs] = useState<object[]>([]);
    const [allBlogsSorting, setAllBlogsSorting] = useState<object[]>([]);

    const [getAllBlogs, { loading, error, data: dataAllBlogs }] = useAllBlog();

    useEffect(() => {
        getAllBlogs({
            fetchPolicy: "cache-and-network"
        })
    }, [])

    useEffect(() => {
        if (dataAllBlogs && "allBlogs" in dataAllBlogs) {
            setAllBlogs([...dataAllBlogs.allBlogs])
        }
    }, [dataAllBlogs])

    useEffect(() => {
        if (allBlogs.length > 0) {
            const filterAllBlogs = sortedData(allBlogs)

            setAllBlogsSorting([...filterAllBlogs])
        }
    }, [allBlogs])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />

            <Container size={"xl"}>
                <Grid>
                    {allBlogsSorting.map((item: any, index) => (
                        <Col key={index} xs={12} sm={6} md={4}>
                            <CardBlog
                                data={item}
                            />
                        </Col>
                    ))}
                </Grid>
            </Container>
        </>
    )
}
