import {Alert, Box, Button, Col, Container, FileInput, Grid, Group, Select, Switch, Title,} from "@mantine/core";
import {Calendar, Check, ChevronDown, X} from "tabler-icons-react";
import React, {useEffect, useState} from "react";
import TextInput from "../component/Input/TextInput";
import Modal, { Props as ModalProps } from "../component/Modal/Modal";
import {useAddMember, useAllClub, useAllTeams} from "@/graphql";
import {DateInput, DatePicker} from "@mantine/dates";
import { useForm } from '@mantine/form';
import dayjs from "dayjs";
import {Notyf} from "notyf";
import Head from "next/head";
import {NavBar} from "@/component/Header";

type Props = {} & ModalProps;

const init = {
    occupation: "",
    classification: "",
    membership_date: "",
    membership_date_end: "",
    person: {
        first_name: "",
        second_name: "",
        third_name: "",
        tribe: "",
        phone: "",
        card_number: "",
        date_birth: ""
    }
}

export default function AddMember (props: Props) {
    const form = useForm({
        initialValues: init
    });
    const [createMember] = useAddMember();
    const [allTeams, setAllTeams] = useState<{label: string, value: string}[]>([]);
    const [allClubs, setAllClubs] = useState<{label: string, value: string}[]>([]);
    const [clubSelected, setClubSelected] = useState<string | null>("");
    const [alert, setAlert] = useState<{ status?: string; msg?: string; code?: string; }>({});

    const [getAllClubs, { loading: loadingAllClubs, error: errorAllClubs, data: dataAllClubs }] = useAllClub();

    useEffect(() => {
        getAllClubs({fetchPolicy: "cache-and-network"})
    }, [])

    useEffect(() => {
        if (dataAllClubs && "allClub" in dataAllClubs) {
            const allClubs: {label: string, value: string}[] = []

            dataAllClubs?.allClub?.map((item: any) => {
                allClubs.push({label: item?.name, value: item?.id})
            })

            setAllClubs([...allClubs])
        }
    }, [dataAllClubs])

    useEffect(() => {
        if (clubSelected) {
            const allTeams: {label: string, value: string, disabled?: boolean}[] = []

            const club = dataAllClubs?.allClub?.filter((item: any) => item.id == clubSelected)

            club?.[0]?.teams?.map((item: any) => {
                allTeams.push({label: item?.name, value: item?.id})
            })

            setAllTeams([...allTeams])
        }
    }, [clubSelected])

    const onSubmit = (data: any) => {
        const {id_team, occupation, classification, membership_date, membership_date_end, person } = data
        const notyf = new Notyf({ position: { x: "right", y: "bottom" } });

        createMember({
            variables: {
                content: {
                    occupation,
                    classification,
                    membership_date: dayjs().format("YYYY-MM-DD"),
                    membership_date_end: dayjs().format("YYYY-MM-DD"),
                    person: {
                        ...person,
                        date_birth: dayjs(person?.date_birth).format("YYYY-MM-DD")
                    },
                    id_team
                }
            },
            onCompleted: () => {
                notyf.success({message: "تم تسجيل عضو الفريق بنجاح", type:"", duration: 10000});
                closeModal();
            },
            onError: ({graphQLErrors}) => {
                if (graphQLErrors?.[0]?.extensions?.code == "CARD_NUMBER_ALREADY_EXISTS") {
                    notyf.open({message: "رقم الهوية موجود مسبقا", type:"error", duration: 10000});
                    setAlert({status: "red", msg: "رقم الهوية موجود مسبقا", code: ""});
                }

                if (graphQLErrors?.[0]?.extensions?.code == "PHONE_NUMBER_ALREADY_EXISTS") {
                    notyf.open({message: "رقم الهاتف موجود مسبقا", type:"error", duration: 10000});
                    setAlert({status: "red", msg: "رقم الهاتف موجود مسبقا", code: ""});
                }
            }
        })
    };

    const closeModal = () => {
        props.onClose();
        form.reset();
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />

            <Container size={"sm"} mb={80} mt={-50}>
                <Title color={"#444"} order={2} ta={"center"} mb={20} >تسجيل عضو فريق</Title>

                {alert.status && (
                    <Alert variant="filled" color={alert.status as string} sx={{ padding: "4px 16px" }} onClose={() => setAlert({})}>
                        {alert.msg}
                    </Alert>
                )}

                <Box sx={({ colors }) => ({padding: 20})}>
                    <form onSubmit={form.onSubmit(onSubmit)} id="submit_form">
                        <Grid gutter={20}>
                            <Col  xs={12} md={6}>
                                <Select
                                    placeholder="حدد النادي"
                                    withAsterisk
                                    rightSection={<ChevronDown size={14} />}
                                    rightSectionWidth={30}
                                    styles={{ rightSection: { pointerEvents: 'none' } }}
                                    data={allClubs}
                                    value={clubSelected}
                                    onChange={setClubSelected}

                                    searchable={true}
                                    clearable={true}

                                    nothingFound="لا يوجد نوادي"
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <Select
                                    placeholder="حدد الفريق"
                                    withAsterisk
                                    rightSection={<ChevronDown size={14} />}
                                    rightSectionWidth={30}
                                    styles={{ rightSection: { pointerEvents: 'none' } }}
                                    data={allTeams}
                                    {...form.getInputProps("id_team")}

                                    searchable={true}
                                    clearable={true}

                                    nothingFound="لا يوجد فرق"
                                />
                            </Col>


                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الاسم الاول"
                                    placeholder="الاسم الاول"
                                    withAsterisk
                                    {...form.getInputProps("person.first_name")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الاسم الثاني"
                                    placeholder="الاسم الثاني"
                                    withAsterisk
                                    {...form.getInputProps("person.second_name")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الاسم الثالث"
                                    placeholder="الاسم الثالث"
                                    withAsterisk
                                    {...form.getInputProps("person.third_name")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="القبيلة"
                                    placeholder="القبيلة"
                                    withAsterisk
                                    {...form.getInputProps("person.tribe")}
                                />
                            </Col>

                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="رقم الهاتف"
                                    placeholder="رقم الهاتف"
                                    withAsterisk
                                    {...form.getInputProps("person.phone")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="رقم البطاقه"
                                    placeholder="رقم البطاقه"
                                    withAsterisk
                                    {...form.getInputProps("person.card_number")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <DateInput
                                    label="تاريخ الميلاد"
                                    placeholder="تاريخ الميلاد"
                                    withAsterisk
                                    valueFormat="MM/DD/YYYY"
                                    icon={<Calendar size={16} />}
                                    {...form.getInputProps("person.date_birth")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الوظيفه"
                                    placeholder="الوظيفه"
                                    withAsterisk
                                    {...form.getInputProps("occupation")}
                                />
                            </Col>

                            <Col  xs={12} md={6}>
                                <Select
                                    label="التصنيف"
                                    placeholder="التصنيف"
                                    withAsterisk
                                    rightSection={<ChevronDown size={14} />}
                                    rightSectionWidth={30}
                                    styles={{ rightSection: { pointerEvents: 'none' } }}
                                    data={['رئيس', 'نائب رئيس', 'عضو', 'امين السر', 'لاعب']}
                                    {...form.getInputProps("classification")}
                                />
                            </Col>


                            <Col span={12}>
                                <Group position={"right"}>
                                    <Button rightIcon={<Check size={15} />} type="submit" form="submit_form">تأكيد</Button>
                                </Group>
                            </Col>
                        </Grid>
                    </form>
                </Box>
            </Container>
        </>
    );
};