import {
    Alert,
    Box,
    Button,
    Col,
    Container,
    FileInput,
    Grid,
    Group,
    Loader,
    Overlay,
    Select,
    Stack,
    Switch,
    Text, Title,
} from "@mantine/core";
import {Calendar, Check, ChevronDown, X} from "tabler-icons-react";
import { Dropzone } from '@mantine/dropzone';
import React, {useEffect, useRef, useState} from "react";
import TextInput from "../component/Input/TextInput";
import Modal, { Props as ModalProps } from "../component/Modal/Modal";
import {useAddTechnical, useAllClub, useAllTeams} from "@/graphql";
import {DateInput, DatePicker} from "@mantine/dates";
import { useForm } from '@mantine/form';
import dayjs from "dayjs";
import {Notyf} from "notyf";
import Head from "next/head";
import {NavBar} from "@/component/Header";

type Props = {} & ModalProps;

const init = {
    occupation: "",
    classification: "",
    membership_date: "",
    membership_date_end: "",
    person: {
        first_name: "",
        second_name: "",
        third_name: "",
        tribe: "",
        phone: "",
        card_number: "",
        date_birth: ""
    }
}

export default function AddTechnicalModal (props: Props) {
    const form = useForm({
        initialValues: init
    });
    const [file, setFile] = useState<File[] | null>(null);
    const openRef = useRef<() => void>(null);
    const [createTechnical] = useAddTechnical();
    const [load, setLoade] = useState(false);
    const [allTeams, setAllTeams] = useState<{label: string, value: string}[]>([]);
    const [allClubs, setAllClubs] = useState<{label: string, value: string}[]>([]);
    const [clubSelected, setClubSelected] = useState<string | null>("");
    const [alert, setAlert] = useState<{ status?: string; msg?: string; code?: string; }>({});

    const [getAllClubs, { loading: loadingAllClubs, error: errorAllClubs, data: dataAllClubs }] = useAllClub();

    useEffect(() => {
        getAllClubs({fetchPolicy: "cache-and-network"})
    }, [getAllClubs])

    useEffect(() => {
        if (dataAllClubs && "allClub" in dataAllClubs) {
            const allClubs: {label: string, value: string}[] = []

            dataAllClubs?.allClub?.map((item: any) => {
                allClubs.push({label: item?.name, value: item?.id})
            })

            setAllClubs([...allClubs])
        }
    }, [dataAllClubs])

    useEffect(() => {
        if (clubSelected) {
            const allTeams: {label: string, value: string, disabled?: boolean}[] = []

            const club = dataAllClubs?.allClub?.filter((item: any) => item.id == clubSelected)

            club?.[0]?.teams?.map((item: any) => {
                allTeams.push({label: item?.name, value: item?.id})
            })

            setAllTeams([...allTeams])
        }
    }, [clubSelected, dataAllClubs?.allClub])

    const onSubmit = (data: any) => {
        setLoade(true)
        const {id_team, occupation, classification, membership_date, membership_date_end, person } = data
        const notyf = new Notyf({ position: { x: "right", y: "bottom" } });

        createTechnical({
            variables: {
                content: {
                    occupation,
                    classification,
                    membership_date: dayjs().format("YYYY-MM-DD"),
                    membership_date_end: dayjs().format("YYYY-MM-DD"),
                    testimony_experience: file?.[0],
                    person: {
                        ...person,
                        date_birth: dayjs(person?.date_birth).format("YYYY-MM-DD")
                    },
                    id_team
                }
            },
            onCompleted: () => {
                notyf.success({message: "تم تسجيل عضو الجهاز فني بنجاح", type:"", duration: 10000});
                closeModal();
            },
            onError: ({graphQLErrors}) => {
                setLoade(false)
                if (graphQLErrors?.[0]?.extensions?.code == "CARD_NUMBER_ALREADY_EXISTS") {
                    notyf.open({message: "رقم الهوية موجود مسبقا", type:"error", duration: 10000});
                    setAlert({status: "red", msg: "رقم الهوية موجود مسبقا", code: ""});
                }

                if (graphQLErrors?.[0]?.extensions?.code == "PHONE_NUMBER_ALREADY_EXISTS") {
                    notyf.open({message: "رقم الهاتف موجود مسبقا", type:"error", duration: 10000});
                    setAlert({status: "red", msg: "رقم الهاتف موجود مسبقا", code: ""});
                }
            }
        })
    };

    const closeModal = () => {
        props.onClose();
        form.reset();
        setFile(null)
        setLoade(false)
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />

            <Container size={"sm"} mb={80} mt={-50}>
                <Title color={"#444"} order={2} ta={"center"} mb={20} >تسجيل عضو جهاز فني</Title>

                {alert.status && (
                    <Alert variant="filled" color={alert.status as string} sx={{ padding: "4px 16px" }} onClose={() => setAlert({})}>
                        {alert.msg}
                    </Alert>
                )}

                {load ?
                    <Overlay opacity={0.9} color="#fff" zIndex={5} >
                        <Stack align={"center"} justify={"center"} h={"100%"} w={"100%"}>
                            <Loader size="xl" variant="dots" />
                            <Text size={"lg"} fw={500}>يتم تحميل الملف يرجى الانتظار</Text>
                        </Stack>
                    </Overlay>
                    : null
                }
                <Box sx={({ colors }) => ({padding: 20})}>
                    <form onSubmit={form.onSubmit(onSubmit)} id="submit_form">
                        <Grid gutter={20}>
                            <Col  xs={12} md={6}>
                                <Select
                                    placeholder="حدد النادي"
                                    withAsterisk
                                    rightSection={<ChevronDown size={14} />}
                                    rightSectionWidth={30}
                                    styles={{ rightSection: { pointerEvents: 'none' } }}
                                    data={allClubs}
                                    value={clubSelected}
                                    onChange={setClubSelected}

                                    searchable={true}
                                    clearable={true}

                                    nothingFound="لا يوجد نوادي"
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <Select
                                    placeholder="حدد الفريق"
                                    withAsterisk
                                    rightSection={<ChevronDown size={14} />}
                                    rightSectionWidth={30}
                                    styles={{ rightSection: { pointerEvents: 'none' } }}
                                    data={allTeams}
                                    {...form.getInputProps("id_team")}

                                    searchable={true}
                                    clearable={true}

                                    nothingFound="لا يوجد فرق"
                                />
                            </Col>


                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الاسم الاول"
                                    placeholder="الاسم الاول"
                                    withAsterisk
                                    {...form.getInputProps("person.first_name")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الاسم الثاني"
                                    placeholder="الاسم الثاني"
                                    withAsterisk
                                    {...form.getInputProps("person.second_name")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الاسم الثالث"
                                    placeholder="الاسم الثالث"
                                    withAsterisk
                                    {...form.getInputProps("person.third_name")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="القبيلة"
                                    placeholder="القبيلة"
                                    withAsterisk
                                    {...form.getInputProps("person.tribe")}
                                />
                            </Col>

                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="رقم الهاتف"
                                    placeholder="رقم الهاتف"
                                    withAsterisk
                                    {...form.getInputProps("person.phone")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="رقم البطاقه"
                                    placeholder="رقم البطاقه"
                                    withAsterisk
                                    {...form.getInputProps("person.card_number")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <DateInput
                                    label="تاريخ الميلاد"
                                    placeholder="تاريخ الميلاد"
                                    withAsterisk
                                    valueFormat="MM/DD/YYYY"
                                    icon={<Calendar size={16} />}
                                    {...form.getInputProps("person.date_birth")}
                                />
                            </Col>
                            <Col  xs={12} md={6}>
                                <TextInput
                                    label="الوظيفه"
                                    placeholder="الوظيفه"
                                    withAsterisk
                                    {...form.getInputProps("occupation")}
                                />
                            </Col>

                            <Col  xs={12} md={6}>
                                <Select
                                    label="التصنيف"
                                    placeholder="التصنيف"
                                    withAsterisk
                                    rightSection={<ChevronDown size={14} />}
                                    rightSectionWidth={30}
                                    styles={{ rightSection: { pointerEvents: 'none' } }}
                                    data={['مدرب', 'مساعد مدرب', 'مدير الفريق', 'مدرب اللياقة', "طبي", "اعلامي"]}
                                    {...form.getInputProps("classification")}
                                />
                            </Col>

                            <Col span={12} >
                                <Text size={"sm"} mb={10} >
                                    شهاده الخبره تدريب (PDF)
                                    {file && file.length > 0
                                        ? <Text size={"md"} fw={700} color={"green"} span={true} mx={5}>تم إضافة الملف</Text>
                                        : null
                                    }
                                </Text>
                                <Dropzone
                                    placeholder={"شهاده الخبره تدريب"}
                                    openRef={openRef}
                                    activateOnClick={false}
                                    multiple={false}
                                    onDrop={(file) => setFile(file)}
                                    styles={{ inner: { pointerEvents: 'all' } }}
                                    accept={{
                                        'application/pdf': ['.pdf'],
                                    }}
                                >
                                    <Group position="center">
                                        <Button onClick={() => {
                                            // @ts-ignore
                                            return openRef ? openRef?.current() : undefined
                                        }}>اختار ملف / اسحب ملف الى هنا</Button>
                                    </Group>
                                </Dropzone>
                            </Col>

                            <Col span={12}>
                                <Group position={"right"}>
                                    <Button rightIcon={<Check size={15} />} type="submit" form="submit_form">تأكيد</Button>
                                </Group>
                            </Col>
                        </Grid>
                    </form>
                </Box>
            </Container>
        </>
    );
};
