import Head from 'next/head'
import { Inter } from 'next/font/google'
import {Box, Col, Container, Grid, Group, MantineTheme, TextInput,} from "@mantine/core";
import React, {useEffect, useState} from "react";
import {useAllStadium} from "@/graphql";
import {searchSortedData, sortedData} from "@/lib/helpers/sort";
import {NavBar} from "@/component/Header";
import {useForm} from "@mantine/form";
import {Search} from "tabler-icons-react";
import {useTheme} from "@emotion/react";
import CardStadium from "@/component/Card/CardStadium";
import {AddReservationsStadium} from "@/component/Modal/AddReservationsStadium";

const inter = Inter({ subsets: ['latin'] })

export default function ReservationsStadium() {
    const {getInputProps, reset, onSubmit, setValues} = useForm({
        initialValues: {
            name: "",
            about: "",
            type: "",
            attachments: "",
            rent: ""
        }
    });
    const theme = useTheme() as MantineTheme;
    const [searchValue, setSearchValue] = useState<string>("");
    const [openAddModal, setOpenAddModal] = useState<boolean>(false);
    const [selectedData, setSelectedData] = useState("");

    const [allStadium, setAllStadium] = useState<object[]>([]);
    const [allStadiumSorting, setAllStadiumSorting] = useState<object[]>([]);

    const [getAllStadium, { loading, error, data: dataAllStadium }] = useAllStadium();

    useEffect(() => {
        getAllStadium()
    }, [getAllStadium])

    useEffect(() => {
        if (dataAllStadium && "allStadiums" in dataAllStadium) {
            setAllStadium([...dataAllStadium.allStadiums])
        }
    }, [dataAllStadium])

    useEffect(() => {
        if (allStadium.length >= 0) {
            const filterAllStadium = sortedData(allStadium)

            setAllStadiumSorting([...filterAllStadium])
        }
    }, [allStadium])

    const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const { value } = event.currentTarget;
        setSearchValue(value);

        const filterAllStadium = searchSortedData(allStadium,['name'], value)
        setAllStadiumSorting([...filterAllStadium])
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />

            <Container size={"xl"}>
                <Box mb={30} mt={"20px"}>
                    <Group position={"apart"}>
                        <TextInput value={searchValue} icon={<Search color={theme.colors.gray[4]} size={16} />} placeholder="بحث" onChange={handleSearchChange}/>


                    </Group>
                </Box>

                <Grid>
                    {allStadiumSorting.map((item: any, index) => (
                        <Col key={index} span={4}>
                            <CardStadium
                                data={item}
                                setOpenAddModal={setOpenAddModal}
                                setSelectedData={setSelectedData}
                            />
                        </Col>
                    ))}
                </Grid>
            </Container>

            <AddReservationsStadium title="حجز ملعب" data={selectedData} opened={openAddModal} onClose={() => setOpenAddModal(false)} />
        </>
    )
}
