import Head from 'next/head'
import {Col, Container, Grid, Group, Image, Title} from "@mantine/core";
import React, {useEffect, useState} from "react";
import {useBlog} from "@/graphql";
import {NavBar} from "@/component/Header";
import {useRouter} from "next/router";
import {RichTextBox} from "@/component/RichTextBox";

export default function Blog() {
    let {query} = useRouter();

    const [blog, setBlog] = useState<any>(null);

    const [getBlog, { loading, error, data: dataBlog }] = useBlog();

    useEffect(() => {
        if (query && "id" in query && query.id !== "") {
            getBlog({
                variables: {
                    id: query.id
                },
                fetchPolicy: "cache-and-network"
            })
        }
    }, [query.id])

    useEffect(() => {
        if (dataBlog && "blog" in dataBlog) {
            setBlog(dataBlog.blog)
        }
    }, [dataBlog])


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />

            <Container size={"xl"}>
                <Grid gutter={20}>
                    <Col span={12} >
                        <Title order={1} fw={"bold"} mb={20}>
                            {blog?.subject}
                        </Title>
                    </Col>

                    {blog?.attachment && blog?.attachment.length  > 0 ?
                        <Col span={12} >
                            <Group spacing={10}>
                                {blog?.attachment?.map((item: any) => (
                                    <Image
                                        key={item?.id}
                                        src={`${process.env.NEXT_PUBLIC_API_URL}/images/${item?.content}`}
                                        width={"100%"} height={"auto"}
                                        styles={{
                                            root: {border: "2px solid #eee", borderRadius: 8},
                                            image: {borderRadius: 8}
                                        }}
                                    />
                                ))}
                            </Group>
                        </Col>
                        : null
                    }

                    <Col span={12} mb={100}>
                        {blog?.description && blog?.description !== ""
                            ? <RichTextBox  content={blog?.description} />
                            : null
                        }
                    </Col>
                </Grid>
            </Container>
        </>
    )
}
