export * from "./useAddTechnical";
export * from "./useUpdateTechnical";
export * from "./useDeleteTechnical";
export * from "./useAllTechnicals";
export * from "./useTechnical";
export * from "./useChangeStatusTechnicalApparatus";
export * from "./useConvertTechnicalToPlayer"
export * from "./useAddAttachmentTechnical";
export * from "./useDeleteAttachmentTechnical";
